<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\IndentityWpf\**" />
    <Compile Remove="ViewModels\Movie\WpfMovie\**" />
    <Compile Remove="ViewModels\Ticket\WpfTicket\**" />
    <Compile Remove="ViewModels\Watchlist\WpfWatchlist\**" />
    <EmbeddedResource Remove="ViewModels\IndentityWpf\**" />
    <EmbeddedResource Remove="ViewModels\Movie\WpfMovie\**" />
    <EmbeddedResource Remove="ViewModels\Ticket\WpfTicket\**" />
    <EmbeddedResource Remove="ViewModels\Watchlist\WpfWatchlist\**" />
    <None Remove="ViewModels\IndentityWpf\**" />
    <None Remove="ViewModels\Movie\WpfMovie\**" />
    <None Remove="ViewModels\Ticket\WpfTicket\**" />
    <None Remove="ViewModels\Watchlist\WpfWatchlist\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CinemaApp.Data\CinemaApp.Data.csproj" />
  </ItemGroup>

</Project>
